# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=1.21.7
loader_version=0.16.14
# Fabric API
fabric_version=0.128.2+1.21.7
# Fabric Kotlin
fabric_kotlin_version=1.13.4+kotlin.2.2.0
# Mod Properties
mod_version=0.1.5
maven_group=io.github.wafarm
archives_base_name=YetAnotherCalculator
